USE [master]
GO
/****** Object:  Database [Todo_Task]    Script Date: 2022/10/11 下午 02:59:38 ******/
CREATE DATABASE [Todo_Task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Todo_Task', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Todo_Task.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Todo_Task_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Todo_Task_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Todo_Task] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Todo_Task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Todo_Task] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Todo_Task] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Todo_Task] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Todo_Task] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Todo_Task] SET ARITHABORT OFF 
GO
ALTER DATABASE [Todo_Task] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Todo_Task] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Todo_Task] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Todo_Task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Todo_Task] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Todo_Task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Todo_Task] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Todo_Task] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Todo_Task] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Todo_Task] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Todo_Task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Todo_Task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Todo_Task] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Todo_Task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Todo_Task] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Todo_Task] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Todo_Task] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Todo_Task] SET RECOVERY FULL 
GO
ALTER DATABASE [Todo_Task] SET  MULTI_USER 
GO
ALTER DATABASE [Todo_Task] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Todo_Task] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Todo_Task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Todo_Task] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Todo_Task] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Todo_Task] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Todo_Task', N'ON'
GO
ALTER DATABASE [Todo_Task] SET QUERY_STORE = OFF
GO
USE [Todo_Task]
GO
/****** Object:  Table [dbo].[User]    Script Date: 2022/10/11 下午 02:59:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[email] [nvarchar](50) NOT NULL,
	[password] [nvarchar](256) NOT NULL,
	[create_time] [datetime] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Login]    Script Date: 2022/10/11 下午 02:59:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[token] [nvarchar](256) NULL,
	[expire_time] [datetime] NULL,
 CONSTRAINT [PK_User_Login] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_User] FOREIGN KEY([Id])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_User]
GO
ALTER TABLE [dbo].[User_Login]  WITH CHECK ADD  CONSTRAINT [FK_User_Login_User_Login] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[User_Login] CHECK CONSTRAINT [FK_User_Login_User_Login]
GO
USE [master]
GO
ALTER DATABASE [Todo_Task] SET  READ_WRITE 
GO
